config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'
  put 'post/:id', to: 'post#update'
  put 'comment/:id', to: 'comment#update'

  resources :home, only: [:index, :show]
  resources :user, only: [:index, :show]
  resources :post, only: [:index, :show, :new, :create, :destroy, :edit]
  resources :comment, only: [:index, :show, :new, :create, :destroy, :edit]

  # Routes for exceptions
  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

    belongs_to :user
    belongs_to :post

    validates :description, presence: true
    # validates :description, length: { maximum: 5000 }

end

app/models/post.rb
class Post < ApplicationRecord

    belongs_to :user
    has_many   :comments, dependent: :delete_all

    validates :title, presence: true
    validates :title, length: { maximum: 150 }
    validates :post_text, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  has_many :posts, dependent: :delete_all
  has_many :comments, dependent: :delete_all

  # Only allow letter, number, underscore and punctuation.
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  validates :username, uniqueness: true

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :authentication_keys => [:username]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :reset_session # TODO: is this what I want?

  before_action :authenticate_user!

  add_flash_types :error, :success # available flash types: notice, alert, error, success

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    added_attrs_login = [:username, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs_login
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
 
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController

    before_action :find_comment, only: [:edit, :update, :destroy]

    def index
      @comments = Comment.all
    end
  
    def show
      @comments = Comment.order(:created_at).where(post_id: params[:id])
      @post = params[:id]
    end

    def edit
    end 

    def update
      @comment.update(params.require(:comment).permit!)
      redirect_to post_path(@comment.post_id)
    end
  
    def new
      @post_id = params[:id]
      @comment = Comment.new
    end
  
    def create
      @comment = Comment.create(params.require(:comment).permit!)
      redirect_to post_path(params[:comment][:post_id])
    end

    def destroy
      @comment.delete
      puts @comment.post_id
      redirect_to post_path(@comment.post_id)
    end
  
    private

    def find_comment
      if defined?(params[:id])
        @comment = Comment.find(params[:id])
      end
    end
    
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController

    def not_found
        render :status => 404
    end

    def unacceptable
        render :status => 422
    end 

    def internal_error
        render :status => 500
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    skip_before_action :authenticate_user!, only: :index

    def index
        if user_signed_in?
            @posts = Post.all.where(user_id: current_user)
        else
            @posts = Post.last(3)
        end
    end

    def show
        puts params
        I18n.locale = params[:id] || I18n.default_locale
        redirect_back(fallback_location: root_path)
    end

end

app/controllers/post_controller.rb
class PostController < ApplicationController  
  
    before_action :find_post, only: [:show, :edit, :update, :destroy]
    
    def index 
      @posts = Post.order(:updated_at).joins(:user).all
    end

    def show
      @comments = @post.comments
      @user = User.find(@post.user_id)
    end
  
    def new
      @post = Post.new
    end

    def edit
    end 

    def update
      @post.update(params.require(:post).permit!)
      redirect_to post_path(@post.id)
    end 
  
    def create
      post = Post.create(params.require(:post).permit!)
      redirect_to root_path if post.persisted?
    end

    def destroy
      @post.destroy
      redirect_to root_path
    end

    private

    def find_post
      if defined?(params[:id])
        @post = Post.find(params[:id])
      end
    end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

    def index
        @users = User.all
    end

    def show
        id = params[:id]
        @posts = Post.where(user_id: id)
        @user = User.find(id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comment/create.html.erb
<h1>Creer</h1>

app/views/comment/delete.html.erb
<h1>Delete</h1>

app/views/comment/edit.html.erb
<h1>Editer le commentaire</h1>

<%= form_for @comment, method: "put" do |f| %>
  <%= f.label t('comment') %><br>
  <%= f.text_area :description, placeholder: 'mon commentaire...' %><br><br>

  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :post_id, value: @comment.post_id%>

  <%= f.submit 'Envoyer' %>
<% end %>

app/views/comment/index.html.erb
<h1>t(comments)</h1>

<%= render partial: 'shared/commentsShow' %>

app/views/comment/new.html.erb
<h2>Formulaire pour un nouveau commentaire</h2>

<%= form_for @comment, :url => { :action => "create" } do |f| %>
  <%= f.text_area :description, placeholder: t('comment') %><br><br>

  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :post_id, value: @post_id %>

  <%= f.submit t('send') %>
<% end %>

app/views/comment/show.html.erb
<h1>Les commentaire de l'article</h1>

<% if user_signed_in? %>
    <%= link_to t(add_comment), new_comment_path(id: @post) %>
<% end %>

<%= render partial: 'shared/commentsShow' %>

app/views/home/index.html.erb
<h1 class="title"><%= t("home") %></h1>

<%= render partial: 'shared/postsShow' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title><%t('title')%></title>
    <meta name="description" content="Retrouvez toute l'atualité de Ruby et ses dérivés sur mon blog. Je vous partage mon expérience et ma passion à travers mes articles réguliers." />
    <link rel="icon" type="image/png" href="assets/img/favicon-16x16.png" sizes="16x16">
    <link rel="icon" type="image/png" href="assets/img/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="assets/img/favicon-96x96.png" sizes="96x96">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,400i,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render partial: 'shared/headMenu' %>

    <div class="container">
        <%= yield %>
    </div>
    
  </body>
</html>

app/views/post/edit.html.erb
<h1>Editer le post</h1>

<%= form_for @post, method: "put" do |f| %>
  <%= f.label t('post_t') %><br>
  <%= f.text_field :title, placeholder: t('post_title') %><br><br>

  <%= f.label t('post_description') %><br>
  <%= f.text_area :description, placeholder: t('post_desc_area') %><br><br>

  <%= f.label t('post_content') %><br>
  <%= f.text_area :post_text, placeholder: t('post_content_area') %><br><br>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <%= f.submit t('edit') %>
<% end %>

app/views/post/index.html.erb
<h1 class="title"><%= t('last_article') %></h1>

<%= render partial: 'shared/postsShow' %>

app/views/post/new.html.erb
<div class="card">
    <h2>Formulaire pour un nouveau post</h2>

    <%= form_for @post, :url => { :action => "create" } do |f| %>
      <%= f.label t('post_t') %><br>
  <%= f.text_field :title, placeholder: t('post_title') %><br><br>

  <%= f.label t('post_description') %><br>
  <%= f.text_area :description, placeholder: t('post_desc_area') %><br><br>

  <%= f.label t('post_content') %><br>
  <%= f.text_area :post_text, placeholder: t('post_content_area') %><br><br>

      <%= f.hidden_field :user_id, value: current_user.id %>

      <%= f.submit t('send') %>
    <% end %>
</div>

app/views/post/show.html.erb
<div class="card">
    <h2><%= @post.title %></h2>
    <span class="username"><%= t('from') %> <%= @user.username %></span>
    <p class="description"><%= @post.description %></p>
    <div class="text">
        <p><%= @post.post_text%></p>
    </div>

    <div class="buttonGroup">
        <% if user_signed_in? %>
            <% if current_user.id == @post.user_id %>
                    <%= button_to t('delete'), {:controller => "post", :action => 'destroy', :id => @post.id, :class => 'delete'}, :confirm => "Are you sure you want to delete it ?", :method => :delete %>
                    <%= link_to t('edite'), edit_post_path(@post.id), :class => 'edit' %>
            <% end %>
        <% end %>

        <% if user_signed_in? %>
            <%= link_to t('add_comment'), new_comment_path(id: @post) %>
        <% end %>

    </div>
</div>

<div>
    <h2><%= t('comments') %></h2>
    <%= render partial: 'shared/commentsShow' %>
</div>

app/views/shared/_commentsShow.html.erb
<% @comments.each do |comment| %>
    <div class="card">
        <p class="commentName"><%= comment.post_id %> - <%= comment.description %></p>
        <div class="articleInfo comment">
            <span><%= t('from') %> <%= comment.user.username %></span>
            <span><%= t('the') %> <%= l comment.created_at, :format => :sample %></span>
        </div>

        <div class="buttonGroup">
            <% if user_signed_in? %>
                <% if current_user.id == comment.user_id || current_user.id == comment.post.user_id%>
                    <%= button_to t('delete'), {:controller => "comment", :action => 'destroy', :id => comment.id}, :confirm => "Are you sure you want to delete it ?", :method => :delete %>
                    <%= link_to t('edite') , edit_comment_path(comment.id) %>
                <% end %>
            <% end %>
        </div>

    </div>
<% end %>

app/views/shared/_headMenu.html.erb
<div class="menu">
  <div class="container">
      <div class="left">
          <p><img src="/assets/ruby-logo.svg" alt="Logo"><%= link_to t("home"), root_path %></p>
      </div>
      <div class="right">

          <% if user_signed_in? %>
            <p class="info" title="Editer mon compte"><%= link_to current_user.username, edit_user_registration_path %></p>
            <p><%= link_to t('user'), user_index_path %></p>
            <p><%= link_to t('last_article'), post_index_path %></p>
            <p><%= link_to t('new_article'), new_post_path %></p>
            <p><%= link_to t('log.out'), destroy_user_session_path, method: :delete %></p>

          <% else %>
            <p><%= link_to t('log.in'), user_session_path, method: :get %></p>
          <% end %>

          <p><%= link_to 'fr', home_path('fr') %></p>
          <p><%= link_to 'en', home_path('en') %></p>
      </div>
  </div>
</div>

app/views/shared/_postsShow.html.erb
<% @posts.each do |post| %>
    <div class="card">
        <h2 class="articleName"><%= post.id %> - <%= post.title %></h2>
        <div class="articleInfo">
            <span class="author"><%= t('from') %> <%= post.user.username %></span>
            <span class="date"><%= t('the') %> <%= l post.updated_at, :format => :sample %></span>
        </div>
        <p class="articleDescription"><%= post.description %></p>

        <div class="buttonGroup">
        <%= link_to t('read_profile'), post_path(post.id), { :class=>"readButton" } %>

        <% if user_signed_in? %>
            <% if current_user.id == post.user_id %>
                    <%= button_to t('delete'), {:controller => "post", :action => 'destroy', :id => post.id}, :confirm => "Are you sure you want to delete it ?", :method => :delete, :class => 'delete' %>
                    <%= link_to t('edite'), edit_post_path(post.id), :class => 'edit' %>
            <% end %>
        <% end %>
        </div>
     </div>
<% end %>

app/views/user/index.html.erb
<h1 class="title">Liste des utilisateurs</h1>

<ul>
<% @users.each do |user| %>
    <li>
        <h2><%= user.username %> - <%= user.id %></h2>
        <p class="mail"><%= t('user_mail') %> : <span><%= user.email %></span></p>
        <%= link_to t('view_profile'), user_path(user.id), :class => 'profilLink' %>
    </li>
<% end %>

app/views/user/show.html.erb
<h2><%= @user.username %> - <%= @user.id %></h2>
<p><%= t('user_mail') %> : <%= @user.email %></p>

<%= render partial: 'shared/postsShow' %>

app/views/users/shared/_links.html.erb
<div class="links">
  <%- if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name) %>
  <% end -%>

  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name) %>
  <% end -%>

  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name) %>
  <% end -%>

  <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %>
  <% end -%>

  <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %>
  <% end -%>

  <%- if devise_mapping.omniauthable? %>
    <%- resource_class.omniauth_providers.each do |provider| %>
      <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %>
    <% end -%>
  <% end -%>
</div>